# Substitua pela sua organização e chave de projeto do SonarQube Cloud
sonar.organization=amilanezes
sonar.projectKey=amilanezes_SEMINARIO-DE-METRICAS-E-MELHORIA-CONTINUA-EM-QUALIDADE-DE-SOFTWARE

sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
