# Substitua pela sua organização e chave de projeto do SonarQube Cloud
sonar.organization=SEU_ORGANIZATION_KEY
sonar.projectKey=SEU_PROJECT_KEY

sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
